# Generated by Django 3.2.25 on 2025-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_partnerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Основное изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес/объем')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('benefits', models.TextField(blank=True, verbose_name='Полезные свойства')),
                ('referral_url', models.URLField(verbose_name='Реферальная ссылка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый товар')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Клики по реферальной ссылке')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='ТенториумРБ', max_length=200, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('page_url', models.URLField(verbose_name='Страница')),
                ('referrer', models.URLField(blank=True, verbose_name='Источник перехода')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Посещение сайта',
                'verbose_name_plural': 'Посещения сайта',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Количество сообщений')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Блог-пост', 'verbose_name_plural': 'Блог-посты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория (старая)', 'verbose_name_plural': 'Категории (старые)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки менеджера'),
        ),
        migrations.AddField(
            model_name='lead',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('phone', 'Телефон'), ('email', 'Email'), ('other', 'Другое')], default='website', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('converted', 'Конверсия'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('document', 'Документ'), ('contact', 'Контакт'), ('location', 'Геолокация')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('is_command', models.BooleanField(default=False, verbose_name='Команда')),
                ('command_name', models.CharField(blank=True, max_length=50, verbose_name='Название команды')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='content.telegramuser')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Сообщения Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Источник перехода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='content.product')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.telegramuser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Просмотр продукта',
                'verbose_name_plural': 'Просмотры продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Источник перехода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_clicks', to='content.product')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.telegramuser', verbose_name='Пользователь Telegram')),
            ],
            options={
                'verbose_name': 'Клик по продукту',
                'verbose_name_plural': 'Клики по продуктам',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='content.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.product', verbose_name='Интерес к товару'),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.telegramuser', verbose_name='Пользователь Telegram'),
        ),
    ]
